
import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Roboto } from 'next/font/google'
import HomeLayout from '@/Layouts/HomeLayouts'
import Main from '@/components/main'


const robota = Roboto({ 
    subsets: ['latin','cyrillic'],
    weight: ['400', '700']
})

const myContex = React.createContext('')

export default function Home() {
  return (
    <>
      <Head>
        <title>House Plans</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
        <HomeLayout>
            <Main></Main>
        </HomeLayout>
    

    </>
  )
}
